### ISSUE TITLE
Compilation errors aren't silenced in a `.tst.ts` file when running `typescript`, but the test still passes with `tstyche`

### ISSUE THREAD

**Issue by erheron** [tstyche/tstyche#13] opened 2023-11-13 11:03 UTC
Hi, and thanks for this awesome library!
We noticed that `.toRaiseError` sometimes doesn't quite work as we expect it to with respect to compilation errors.
We're not sure if there is a bug, or some better documentation is needed 🤔 

### Reproduction
/// file sample.tst.ts

```ts
import { expect, test } from 'tstyche';

function id(arg: number): number {
	return arg;
}

test('Cannot call "id" function with an argument of type string', () => {
	// Full error underneath: "Argument of type `string` is not assignable to parameter of type `number`."
	expect(id('123')).type.toRaiseError('Argument'); 
	expect(id('123')).type.toRaiseError(); 
});
```

And then when we run `yarn tsc`, the result is
```bash
src/__typetests__/sample.tst.ts:9:12 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.

9  expect(id('123')).type.toRaiseError('Argument');
             ~~~~~

src/__typetests__/sample.tst.ts:10:12 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.

10  expect(id('123')).type.toRaiseError();
```
However, running `yarn tstyche` gives an expected output:

```bash
❯ yarn tstyche
yarn run v1.22.19
$ /Users/..../.bin/tstyche
uses TypeScript 5.2.2 with ./tsconfig.json

pass ./src/__typetests__/sample.tst.ts
  + Cannot call id function with an argument of type string

Targets:    1 passed, 1 total
Test files: 1 passed, 1 total
Tests:      1 passed, 1 total
Assertions: 2 passed, 2 total
Duration:   11.1s

Ran all test files.
✨  Done in 12.66s.
```

### Packages
```bash
typescript@5.2.2
tstyche@1.0.0-beta.1
```

**Comment by mrazauskas** [comment] 2023-11-13 11:10
Do you get it right, you would expect to see no error in `tsc`s output? Hm.. It does not know anything about `tstyche`, so it reports the error.

Why do you run `tsc` on a type test? (;

**Comment by mrazauskas** [comment] 2023-11-13 11:11
Thanks for giving for TSTyche! It is a fresh library, can be documentation is missing some clarity. Let’s figure this out.

**Comment by erheron** [comment] 2023-11-13 11:29
> Do you get it right, you would expect to see no error in tscs output? Hm.. It does not know anything about tstyche, so it reports the error.

You're right. After giving it a second thought, that was a bit of an unfair expectation 😬 

> Why do you run tsc on a type test? (;

It's valuable for us to get autocomplete and other help from Typescript when writing a test (think of a normal unit test -- would you like it to write it without TSC?). Please note that if this would be another type test (not the one with `.toRaiseError`), running typescript on it probably wouldn't make any difference. 

I see your suggestion to not run TSC on type test files 🙌🏻
I'd like to think of it as a last resort, due to a worse DevEx. 
If nothing more comes to mind, though, we'll give it a go. Maybe I'm being too pessimistic about that "bad DevEx"

**Comment by mrazauskas** [comment] 2023-11-13 11:43
Wait.. Autocompletions should be there. TypeScript provides these through language service. That is just a technical detail, `tsc` is the TypeScript compiler.

Are you trying to say that the errors should not be highlighted in IDE, if they are matched by `.toRaiseError()`? This will be fixed in some 2-3 months. I have a working prototype.

**Comment by erheron** [comment] 2023-11-13 13:00
> Wait.. Autocompletions should be there. TypeScript provides these through language service. That is just a technical detail, tsc is the TypeScript compiler.

Yeah sorry, I mixed things up a little, but here's what I meant:

1. I thought it would be best if I can both compile this file with `tsc` __and__ run it with `tstyche`. That does not seem to be possible (cause' as you said, TS does not know nothing about `tstyche`).
2. Yes, it would be nice if errors are not highlighted in the IDE and language service still works. If there's a working prototype for that, I'm more than happy to wait 🚀

**Comment by mrazauskas** [comment] 2023-11-13 13:18
Thanks!

It still feels puzzling for me why you want to pass test files through `tsc`? Are you trying to type check them? There is no need, because `tstyche` does that for you. It will pick up all syntactic and semantic errors just like `tsc`. Try it out (also on different versions of compiler, e.g. `tstyche --target 4.8,latest`).

And there is more:

```ts
import { expect, test } from "tstyche";

test.skip("is skipped?", () => {
  const a: string = 123; // obviously a type error, but it will be skipped

  // ...
});
```

If a test is skipped, `tstyche` does not report type errors in that particular test. This is why it is a type test runner.

**Comment by mrazauskas** [comment] 2023-11-15 11:06
Yes, the watch mode is planned for version 2. I have a working draft, but it needs more thinking.

**Comment by mrazauskas** [comment] 2023-11-16 11:14
To make it easier to track the progress, I open these issues:
- https://github.com/tstyche/tstyche/issues/16
- https://github.com/tstyche/tstyche/issues/17

Add a couple of sentences will be added to the documentation website as well.

**Comment by mrazauskas** [comment] 2024-06-10 14:43
TSTyche 2 shipped today. It has the watch mode. Give it a try! For feedback I opened #222.

Also I opened #224 to track progress on ability matchers. This is the next milestone. Thanks for starting this discussion.

I think it is time to close this issue. Is there is anything you would like to ask, feel free to leave a message here or opening new issue.

**Closed by mrazauskas** 2024-06-10 14:43 UTC

**Comment by olsonpm** [comment] 2025-07-31 15:46
Hey @mrazauskas - regarding

> I would suggest using the toBeCallableWith() matcher, because it indicates the purpose of the test.

one thing I like about `toRaiseError` is that the reason is explicit.  i.e. I can confirm *why* it's not callable.  Do you have any plans on supporting that use-case ?

---

unrelated - tstyche has been working great.  I'm upgrading from 2 -> 4 now, thanks so much for this library

**Comment by mrazauskas** [comment] 2025-07-31 17:09
All is fine. Thanks for asking.
